default:
  tags:
    - on-prem

stages:
  - test

# test:conda-build:
#   stage: test
#   image:
#     name: continuumio/miniconda3:23.10.0-1
#   script:
#     - conda env create -f toxic-comments-severity-conda-env.yaml -p ./conda/toxic-comments-severity
#   rules:
#     - if: $CI_MERGE_REQUEST_IID
#       changes:
#         - toxic-comments-severity-conda-env.yaml
#     - if: $CI_PIPELINE_SOURCE == "push"
#     - if: $CI_PIPELINE_SOURCE == "web"
#     - if: $CI_COMMIT_TAG
#       when: never
#   artifacts:
#     paths:
#       - ./conda
#   needs: []

test:pylint-pytest:
  stage: test
  image:
    name: continuumio/miniconda3:23.10.0-1
  before_script:
    - pdm install
    - source ./venv/bin/activate
  script:
    - pylint src --fail-under=7.0 --ignore=tests --disable=W1202
    - pytest src/tests
  rules:
    - if: $CI_MERGE_REQUEST_IID
      changes:
        - src/**/*
        - conf/**/*
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_COMMIT_TAG
      when: never

# pages:
#   stage: deploy-docs
#   image:
#     name: continuumio/miniconda3:23.10.0-1
#   before_script:
#     - source activate ./conda/toxic-comments-severity
#     - pip install -r docs-requirements.txt
#   script:
#     - sphinx-apidoc -f -o docs src
#     - sphinx-build -b html docs public
#   artifacts:
#     paths:
#     - public
#   only:
#     - main
#   needs:
#     - test:conda-build

# build:data-prep-image:
#   stage: build
#   image:
#     name: gcr.io/kaniko-project/executor:debug
#     entrypoint: [""]
#   before_script:
#     - "[[ -z ${HARBOR_ROBOT_CREDS_JSON} ]] && echo 'HARBOR_ROBOT_CREDS_JSON variable is not set.' && exit 1"
#   script:
#     - mkdir -p /kaniko/.docker
#     - cat $HARBOR_ROBOT_CREDS_JSON > /kaniko/.docker/config.json
#     - >-
#       /kaniko/executor
#       --context "${CI_PROJECT_DIR}"
#       --dockerfile "${CI_PROJECT_DIR}/docker/toxic-comments-severity-data-prep.Dockerfile"
#       --destination "registry.aisingapore.net/aiap-15-dsp/toxic/data-prep:${CI_COMMIT_SHORT_SHA}"
#   rules:
#     - if: $CI_MERGE_REQUEST_IID
#       changes:
#         - docker/toxic-comments-severity-data-prep.Dockerfile
#         - src/**/*
#         - conf/**/*
#     - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
#     - if: $CI_PIPELINE_SOURCE == "web" && $BUILD_ALL
#     - if: $CI_PIPELINE_SOURCE == "web" && $BUILD_DATAPREP
#   needs:
#     - test:pylint-pytest

# build:model-training-image:
#   stage: build
#   image:
#     name: gcr.io/kaniko-project/executor:debug
#     entrypoint: [""]
#   before_script:
#     - "[[ -z ${HARBOR_ROBOT_CREDS_JSON} ]] && echo 'HARBOR_ROBOT_CREDS_JSON variable is not set.' && exit 1"
#   script:
#     - mkdir -p /kaniko/.docker
#     - cat $HARBOR_ROBOT_CREDS_JSON > /kaniko/.docker/config.json
#     - >-
#       /kaniko/executor
#       --context "${CI_PROJECT_DIR}"
#       --dockerfile "${CI_PROJECT_DIR}/docker/toxic-comments-severity-model-training.Dockerfile"
#       --destination "registry.aisingapore.net/aiap-15-dsp/toxic/model-training:${CI_COMMIT_SHORT_SHA}"
#   rules:
#     - if: $CI_MERGE_REQUEST_IID
#       changes:
#         - docker/toxic-comments-severity-model-training.Dockerfile
#         - src/**/*
#         - conf/**/*
#     - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
#     - if: $CI_PIPELINE_SOURCE == "web" && $BUILD_ALL
#     - if: $CI_PIPELINE_SOURCE == "web" && $BUILD_MODEL
#   needs:
#     - test:pylint-pytest

# build:retag-images:
#   stage: build
#   image:
#     name: gcr.io/go-containerregistry/crane:debug
#     entrypoint: [""]
#   before_script:
#     - "[[ -z ${HARBOR_ROBOT_CREDS_JSON} ]] && echo 'HARBOR_ROBOT_CREDS_JSON variable is not set.' && exit 1"
#   script:
#     - cat $HARBOR_ROBOT_CREDS_JSON > /root/.docker/config.json
#     - crane tag registry.aisingapore.net/aiap-15-dsp/toxic/data-prep:${CI_COMMIT_SHORT_SHA} ${CI_COMMIT_TAG}
#     - crane tag registry.aisingapore.net/aiap-15-dsp/toxic/model-training:${CI_COMMIT_SHORT_SHA} ${CI_COMMIT_TAG}
#   rules:
#     - if: $CI_COMMIT_TAG && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
